fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=

dags:
  gitSync:
    enabled: true
    repo: https://github.com/sthefanyspina/DataEngineeringProjects/tree/main/Kubernetes/Kubernetes_Data_Engineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"